name: Deploy Visitor Counter App

on:
  push:
    branches: [ master]

jobs:
  deploy:
    name: EC2 Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Deploy 
        env: 
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: | 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${IP_ADDRESS} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/ &&
              rm -rf SCA_Devops_Python_Project
              git clone https://github.com/maryjonah/SCA_Devops_Python_Project.git
              cd SCA_Devops_Python_Project
              git checkout master &&
              git reset --hard origin/master &&
              git pull origin master &&
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              flask run --host=0.0.0.0
              '