name: Deploy Visitor Counter App

on:
  push:
    branches: [ master]

jobs:
  deploy:
    name: EC2 Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy 
        uses: actions/checkout@v2
        env: 
          PRIVATE_KEY: {{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: | 
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/sca-devops-project &&
              git checkout master &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
              python3 app.py
              '